# Generated by Django 3.0.7 on 2020-07-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200707_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='OfferPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='product',
            name='Rating',
            field=models.FloatField(),
        ),
    ]
