# Generated by Django 3.0.7 on 2020-07-10 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200708_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='Product',
        ),
        migrations.AddField(
            model_name='ratings',
            name='Product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
    ]
