# Generated by Django 3.0.7 on 2020-07-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200711_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='onHomeScreen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Catagory',
            field=models.CharField(max_length=70),
        ),
    ]
