# Generated by Django 3.0.7 on 2020-07-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200712_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Product',
            field=models.CharField(max_length=100),
        ),
    ]
