# Generated by Django 3.0.7 on 2020-07-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Description10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Description4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Description5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Description6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Description7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Description8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Description9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploadedimages'),
        ),
        migrations.AddField(
            model_name='product',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploadedimages'),
        ),
        migrations.AddField(
            model_name='product',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploadedimages'),
        ),
        migrations.AddField(
            model_name='product',
            name='Image4',
            field=models.ImageField(blank=True, null=True, upload_to='uploadedimages'),
        ),
        migrations.AddField(
            model_name='product',
            name='Image5',
            field=models.ImageField(blank=True, null=True, upload_to='uploadedimages'),
        ),
        migrations.AddField(
            model_name='product',
            name='Title1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Title10',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Title2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Title3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Title4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Title5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Title6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Title7',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Title8',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Title9',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='Rating',
            field=models.FloatField(null=True),
        ),
    ]
