# Generated by Django 3.0.7 on 2020-07-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200716_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(null=True, upload_to='uploadedprofileimage'),
        ),
    ]
